## Administrative Boundaries

See DuckDB + Jupyter setup instructions here: https://duckdb.org/docs/guides/python/jupyter.html

Download Administrative Boundaries from Overture and write them out as GeoJSON

In [3]:
import duckdb, shapely, json
import pandas as pd
import geopandas as gpd

In [4]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False

In [5]:
%sql duckdb:///:default:

In [6]:
%%sql
INSTALL httpfs;
INSTALL spatial;
LOAD httpfs;
LOAD spatial;

SET s3_region='us-west-2';
SET s3_access_key_id="ASIATASCDNMSYSILCT5U";
SET s3_secret_access_key="bIdL8/suaHtlIomdDQm3wrDlpO0X2pj0gXg5hdJ9";
SET s3_session_token="IQoJb3JpZ2luX2VjEDgaCXVzLWVhc3QtMiJHMEUCIEorZUgVGoSAWEXezt0aGnNqX+jKyDs8I1w9n+Hfs7wYAiEA47HgVDCIndtJdMbZ/8g8TbQGi7zdNMYF0ACrNC90oVAq+AMIwf//////////ARAAGgwyMDczNzA4MDgxMDEiDMw+8G6R8xEqqb+2+yrMA5JTfoMeTRFMar5jOqa3li7nfze+IdpDobLq4IQ+Nf4zU+jup+09VNrFs54+rP3tU2ZZMRP2hmByb4wSly58JkbfvlKGYAGTxe/Iut5cRHzRq+IzEgZ7Ee7sI5aaqHFZPo+bjOyaq9PUD9ZlAs9wSbjCfMCYdcEVF6PmNAPPHNTV3YhRHIXN0bM0QfPptMDE8nxGjsyhOwwsLITLGzk8xUfyCLfHNQcGO4Vn1OU8WSwh7wLWfj5whw4V3RElj+tGAzl6VcrqvIeR3Q/zEE73fTQNQNTTlOYXER80cziTAP/gyQXoslhQPLg5P4X6WWgo8B+D7UmwY3nmldROvaT2eaUzHyPp2OdGvrGcxiMRjHduP9Q6ekwQIjvr0uBZM+iwMbjr1tfCQHUBTuQuOfyZnB81yl1hN6zgAFXDotOWvHKfv9lc1J+AaaLvR1ZPrnNt7tVMNIzye+OoqSQhyAPCzQEnHHNeVnVxPJ2En5cPI73oyO0LGJBrI1duipFIJu2Ser/+Kf58J6ZNBQE/DNvL+LpcWFZviqLps3MIOa+YateDvP7thu5MurT7Q8prFUykBafda0Z6cDvBKzeV8rUAkYBXY72I35bGjF3rGLUwz9/qpQY6pgFkV8vkSoxLbcNGqSOBGBgiAR4mDYUlplFWs3AoHzfaJZ3DKxFC6rDHBGhBYIvALRKBWYlvAsregx6bZmuxM9638WH1WFokHSWy5CeX9NOMT9tdwjjmGEpAua4h6mYIKvMgbaovbmMIMe5lq0U+ueTB2+JGHA024vkqxdI1/mzjr+qxolXAa3ZauzigQkHWS83wEz8JMeTvGcooQ/r+x9L8FmqIMjZp";

Empty DataFrame
Columns: []
Index: []

### Step 1: Create DataFrame by querying parquet files on S3.
For now, just `select *` to get everything

In [9]:
%%sql df <<
SELECT 
    *
FROM
    read_parquet('s3://omf-internal-usw2/staging/admins/type=*/*', hive_partitioning=1)
WHERE 
    ST_INTERSECTS(
        ST_GeomFromText('POLYGON((-125.84156914226372 49.88287878391259,-119.67641816779683 49.96561294866558,-119.70454325627813 45.12022093154354,-125.91470533726195 45.09472148286409,-125.84156914226372 49.88287878391259))'),
        ST_GeomFromText(geometry)
    )

In [12]:
print(len(df))
df.head(2)

67

,id,adminlevel,maritime,subtype,localitytype,names,context,isocountrycodealpha2,isosubcountrycode,defaultlanguage,drivingside,version,updatetime,sources,geometry,bbox,type
0,8528d273fffffff1100000000000001,2,None,None,None,None,None,None,None,None,None,0,2023-07-03T11:59:05.775Z,"[{'key': ['dataset', 'property'], 'value': ['T...","LINESTRING (-119.919252 49.000032, -119.924567...","{'minx': -119.949108, 'maxx': -119.919252, 'mi...",administrativeBoundary
1,8428d27ffffffff1100000000000001,2,None,None,None,None,None,None,None,None,None,0,2023-07-03T11:59:05.775Z,"[{'key': ['dataset', 'property'], 'value': ['T...","LINESTRING (-119.736733 49.000361, -119.739005...","{'minx': -119.919252, 'maxx': -119.736733, 'mi...",administrativeBoundary

In [13]:
# Convert it to a GeoDataFrame
df['geometry'] = df.geometry.apply(shapely.wkt.loads)
gdf = gpd.GeoDataFrame(df)

In [23]:
gdf[gdf['type']=='locality']

,id,adminlevel,maritime,subtype,localitytype,names,context,isocountrycodealpha2,isosubcountrycode,defaultlanguage,drivingside,version,updatetime,sources,geometry,bbox,type
62,8029fffffffffff1200000000000006,4,None,administrativeLocality,state,"{'key': ['common'], 'value': [[{'key': ['value...",8029fffffffffff1200000000000002,None,US-WA,en-Latn,None,0,2023-05-29T16:10:19.780Z,"[{'key': ['dataset', 'property'], 'value': ['T...","MULTIPOLYGON (((-124.84897 48.18137, -124.8485...","{'minx': -124.848975, 'maxx': -116.915989, 'mi...",locality
63,8003fffffffffff1200000000000002,2,None,administrativeLocality,country,"{'key': ['common'], 'value': [[{'key': ['value...",PlanetId,CA,None,en-Latn,right,0,2023-05-27T15:44:34.535Z,"[{'key': ['dataset', 'property'], 'value': ['T...","MULTIPOLYGON (((-141.56109 89.99990, -141.5376...","{'minx': -141.5610942, 'maxx': -51.053519, 'mi...",locality
64,8029fffffffffff1200000000000007,4,None,administrativeLocality,state,"{'key': ['common'], 'value': [[{'key': ['value...",8029fffffffffff1200000000000002,None,US-OR,en-Latn,None,0,2023-05-29T14:53:16.397Z,"[{'key': ['dataset', 'property'], 'value': ['T...","MULTIPOLYGON (((-124.70354 42.77037, -124.7029...","{'minx': -124.703541, 'maxx': -116.463262, 'mi...",locality
65,8013fffffffffff1200000000000003,4,None,administrativeLocality,province,"{'key': ['common'], 'value': [[{'key': ['value...",8003fffffffffff1200000000000002,None,CA-BC,en-Latn,None,0,2023-05-26T16:53:41.451Z,"[{'key': ['dataset', 'property'], 'value': ['T...","MULTIPOLYGON (((-139.06097 59.99885, -139.0487...","{'minx': -139.060971, 'maxx': -114.054252, 'mi...",locality
66,8029fffffffffff1200000000000002,2,None,administrativeLocality,country,"{'key': ['common'], 'value': [[{'key': ['value...",PlanetId,US,None,en-Latn,right,0,2023-07-03T11:59:05.775Z,"[{'key': ['dataset', 'property'], 'value': ['T...","MULTIPOLYGON (((-179.23109 51.26753, -179.2285...","{'minx': -179.231086, 'maxx': 179.859685, 'min...",locality

In [ ]:
# # Unserialize JSON where it was serialized
# gdf.names = gdf.names.apply(json.loads)
# gdf.sources = gdf.sources.apply(json.loads)
# gdf.categories = gdf.categories.apply(json.loads)
# gdf.addresses = gdf.addresses.apply(json.loads)

In [17]:
gdf.head().geometry.type

0    LineString
1    LineString
2    LineString
3    LineString
4    LineString
dtype: object